dotenv: .env
networks:
  default: 'development'
  development:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}

# compiler default configuration
compiler:
  evm_version: null
  solc:
    version: null
    optimizer:
      enabled: true
      runs: 200
  vyper:
    version: null
